// <auto-generated />
using System;
using CoinCounting.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoinCounting_Data.Migrations
{
    [DbContext(typeof(CoinContext))]
    [Migration("20220304000933_AddDateTimeToCoinDeposits")]
    partial class AddDateTimeToCoinDeposits
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CoinCounting.Data.CoinDeposit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTimeOffset>("DateDesposited")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Dimes")
                        .HasColumnType("int");

                    b.Property<int>("Nickels")
                        .HasColumnType("int");

                    b.Property<int>("Pennies")
                        .HasColumnType("int");

                    b.Property<int>("Quarters")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CoinDeposits");
                });

            modelBuilder.Entity("CoinCounting.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CoinCounting.Data.CoinDeposit", b =>
                {
                    b.HasOne("CoinCounting.Data.User", "User")
                        .WithMany("CoinDeposits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoinCounting.Data.User", b =>
                {
                    b.Navigation("CoinDeposits");
                });
#pragma warning restore 612, 618
        }
    }
}
